language:        node_js
node_js:
  - "10"
  - "11"
  - "stable"
services:
  - mongodb
script:
  - npm run setup
  - npm test
  - npm run build
  # - npm run start
cache:
  directories:
  - node_modules
  - packages/create-react-app/node_modules
  - packages/react-scripts/node_modules
deploy:
  provider:      releases
  repo:          answart/voting-redux
  target_branch: master
  name:          Alexandra Swart
  email:         answart@sbcglobal.net
  skip_cleanup:  true
  github_token:  $github_token
branches:
  only:
    - master
