language: node_js
node_js:
  - '10'
  - '11'
  - stable
services: mongodb
script:
  - npm run setup
  - npm run build
  - echo "Running tests against $(node -v)..."
after_success: npm run test
cache:
  directories:
  - node_modules
  - client/node_modules
  - server/node_modules
  - packages/create-react-app/node_modules
  - packages/react-scripts/node_modules
deploy:
  provider: heroku
  app: $HEROKU_APP_NAME
  api_key:
    secure: $HEROKU_API_KEY
branches:
  only:
  - master
# jobs:
#   include:
#     - stage: Produce Coverage
#       node_js: node
#       script: npm run coveralls