language: node_js
node_js:
  - '10'
  - '11'
  - stable
services: mongodb
script:
  - npm run setup
  - npm run build
  - echo "Running tests against $(node -v)..."
after_success: npm run coveralls
cache:
  directories:
  - node_modules
  - client/node_modules
  - server/node_modules
  - packages/react-scripts/node_modules
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: answart-voting-app
  on:
    repo: Answart/voting-redux
branches:
  only:
  - master