language: node_js
node_js:
  - "10"
  - "11"
  - "stable"
script:
  - npm run build
  - npm run start
branches:
  only:
    - master
cache:
  directories:
  - node_modules
after_success: npm run test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
